SELECT COUNT(p.petid), count(p.BREEDID), COUNT(p.SPECIESID), s.SPECIES_NAME, b.BREED_NAME
FROM OWNER o JOIN PET p ON 
  o.OWNERID = p.OWNERID
    JOIN ANIMAL_SPECIES s ON
      p.SPECIESID = s.SPECIESID
        JOIN ANIMAL_BREED b ON 
          s.SPECIESID = b.SPECIESID
GROUP BY CUBE (p.petid, s.SPECIES_NAME, b.BREED_NAME);
  
  




  SELECT OWNERID, BREEDID, SPECIESID, COUNT(SPECIESID), COUNT(BREEDID)
  FROM PET
    WHERE OWNERID = 71
  GROUP BY GROUPING SETS ( OWNERID, BREEDID, SPECIESID)


  --VIEW SHOULD HAVE SPECIES/BREED OF DEAD PET AND THEN SPECIES BREEDS OF ALL PETS INCLUDING THE DEAD ONE