CREATE OR REPLACE FUNCTION FUNC_DRUGNAME(f_drugid IN PHARMACOLOGY_STOCK.DRUGID%TYPE)
RETURN VARCHAR2
AS
lv_drugname varchar2(2000) := NULL;
BEGIN
	SELECT DRUG_NAME
	INTO lv_drugname
	FROM PHARMACOLOGY_STOCK
	WHERE DRUGID = f_drugid;
RETURN lv_drugname;

EXCEPTION
	WHEN NO_DATA_FOUND THEN
	RETURN NULL;
END;
