CREATE OR REPLACE FUNCTION FUNC_INVNUM(p_petid IN ANIMAL_FACTS.PETID%TYPE)
RETURN INT
AS
	lv_invnum INVOICE_OPEN.INVOICEID%TYPE := NULL;
BEGIN
	PROC_GETINVNUM(p_petid, lv_invnum);
RETURN lv_invnum;

END