CREATE SEQUENCE breedid_seq
  MINVALUE 1
  MAXVALUE 99999
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE speciesid_seq
  MINVALUE 1
  MAXVALUE 99999
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE genderid_seq
  MINVALUE 1
  MAXVALUE 20
  START WITH 1
  INCREMENT BY 1
  NOCACHE;


CREATE SEQUENCE prescription_seq
MINVALUE 1
START WITH 1000
INCREMENT BY 3
NOCACHE;


ALTER TABLE ANIMAL_GENDER
MODIFY GENDERID int DEFAULT genderid_seq.NEXTVAL;


CREATE SEQUENCE laborderid_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE estimate_seq
MINVALUE 100
START WITH 100
INCREMENT BY 1
NOCACHE;


CREATE SEQUENCE invoice_seq
START WITH 1000
INCREMENT BY 1
NOCACHE;