CREATE OR REPLACE TRIGGER RXORDER_CONTROLLED_TRIG
AFTER INSERT ON RX_ORDER 
REFERENCING NEW AS NEW




DECLARE
lv_iscontrolled PHARMACOLOGY_STOCK.IS_CONTROLLED%TYPE;
lv_drug_units_pre RX_ORDER.DRUG_UNITS_PRESCRIBED%TYPE;
lv_rx_order_tpd RX_ORDER.TIMES_PER_DAY%TYPE;


ex_controlled_14 EXCEPTION;

BEGIN
SELECT IS_CONTROLLED
INTO lv_iscontrolled
FROM PHARMACOLOGY_STOCK;

SELECT RX_ORDER.TIMES_PER_DAY, RX_ORDER.DRUG_UNITS_PRESCRIBED
INTO  lv_rx_order_tpd, lv_drug_units_pre
FROM RX_ORDER;

IF  lv_iscontrolled IN ('y', 'Y', '1') AND (lv_drug_units_pre/lv_rx_order_tpd) > 14  THEN
	RAISE ex_controlled_14;
END IF;

EXCEPTION
	WHEN ex_controlled_14 then DBMS_OUTPUT.PUT_LINE('fart');
--	--PUT INTO NOTES RX CANNOT BE FILLED, DUE TO TOO MANY DAYS AND A CONTROLLED ALSO MAKE A NOTES COLUMN FOR THE RX_ORDER
	--SET ALL 3 COLUMNS EQUAL TO NULL
	
END;