create or replace TRIGGER PET_FACTS_UPDATE_TRIG 
AFTER UPDATE OF BIRTH_DATE,BREEDID,COLORING,GENDERID, OWNERID, PET_FIRST_NAME, PET_MIDDLE_NAME, SPECIESID, TEMPERAMENT_NOTES ON PET 

DECLARE 
lv_petid int; 

BEGIN
/*
We are using a "WHERE EXISTS" because we want the statement to find all rows that exist in in the table we are checking
and update them based on the values of the table that we have UPDATED */

UPDATE ANIMAL_FACTS 
SET ( BIRTH_DATE,BREEDID,COLORING,GENDERID,PET_FIRST_NAME, PET_MIDDLE_NAME, SPECIESID, TEMPERAMENT_NOTES)
= ( SELECT BIRTH_DATE,BREEDID,COLORING,GENDERID, PET_FIRST_NAME,PET_MIDDLE_NAME,SPECIESID,TEMPERAMENT_NOTES
FROM PET
WHERE ANIMAL_FACTS.PETID = PET.PETID)

WHERE EXISTS ( SELECT BIRTH_DATE,BREEDID,COLORING,GENDERID, PET_FIRST_NAME,PET_MIDDLE_NAME,SPECIESID,TEMPERAMENT_NOTES
FROM PET
WHERE ANIMAL_FACTS.PETID = PET.PETID);

END;