CREATE OR REPLACE DIRECTORY 
RADIMG
AS 
	'D:/Put_Stuff_Here/Images';




UPDATE RADIOLOGY_HISTORY
SET RADIMG_FILES = BFILENAME('RADIMG', 'xray_snek.jpg')
WHERE RADIMGID = 1;

UPDATE RADIOLOGY_HISTORY
SET RADIMG_FILES = BFILENAME('RADIMG', 'dog_Brain-MRI.jpeg')
WHERE RADIMGID = 2;

UPDATE RADIOLOGY_HISTORY
SET RADIMG_FILES = BFILENAME('RADIMG', 'feline_PET SCAN.jpg')
WHERE RADIMGID = 3;

UPDATE RADIOLOGY_HISTORY
SET RADIMG_FILES = BFILENAME('RADIMG', 'monitorlizard_catscan.jpg')
WHERE RADIMGID = 4;




CREATE OR REPLACE DIRECTORY
IMPORTCHART
AS
	'D:/Put_Stuff_Here/PDF/';