INSERT INTO ANIMAL_GENDER (GENDER_NAME) VALUES('Female');

INSERT INTO ANIMAL_GENDER (GENDER_NAME) VALUES('Female Spayed');

INSERT INTO ANIMAL_GENDER (GENDER_NAME) VALUES( 'Male');

INSERT INTO ANIMAL_GENDER (GENDER_NAME) VALUES( 'Male Neuter');

INSERT INTO ANIMAL_GENDER (GENDER_NAME) VALUES( 'Indeterminate');

INSERT INTO ANIMAL_GENDER (GENDER_NAME) VALUES( 'Geneitc Hermaphrodite');

SELECT *
FROM ANIMAL_GENDER
ORDER BY GENDER_NAME;



