	SELECT PET.PETID,  PET.PET_FIRST_NAME,  PET.PET_MIDDLE_NAME,  PET.SPECIESID,  PET.BREEDID,  PET.GENDERID,  PET.COLORING,  PET.BIRTH_DATE,
  		PET.TEMPERAMENT_NOTES
	FROM PET
UNION ALL
  	SELECT ANIMAL_FACTS.PETID,  ANIMAL_FACTS.PET_FIRST_NAME,  ANIMAL_FACTS.PET_MIDDLE_NAME,  ANIMAL_FACTS.SPECIESID,  ANIMAL_FACTS.BREEDID,  ANIMAL_FACTS.GENDERID,  ANIMAL_FACTS.COLORING,
  		ANIMAL_FACTS.BIRTH_DATE,  ANIMAL_FACTS.TEMPERAMENT_NOTES
  	FROM ANIMAL_FACTS;



INSERT INTO PET(OWNERID, PET_FIRST_NAME)
VALUES(71, 'Suzie');
INSERT INTO PET(OWNERID, PET_FIRST_NAME)
VALUES(71, 'Marisol');
INSERT INTO PET(OWNERID, PET_FIRST_NAME)
VALUES(71, 'Jeffery');
INSERT INTO PET(OWNERID, PET_FIRST_NAME)
VALUES(59, 'Jason');
INSERT INTO PET(OWNERID, PET_FIRST_NAME)
VALUES(99, 'Hillary');
INSERT INTO PET(OWNERID, PET_FIRST_NAME)
VALUES(257, 'Wade');
INSERT INTO PET(OWNERID, PET_FIRST_NAME)
VALUES(186, 'Rover');
INSERT INTO PET(OWNERID, PET_FIRST_NAME)
VALUES(186, 'Tweety');


UPDATE "DAVEDBA"."PET" SET SPECIESID = '2', BREEDID = '47', GENDERID = '2', COLORING = 'Black', BIRTH_DATE = TO_DATE('2016-12-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), IS_LIVING = '1' WHERE ROWID = 'AAAWmCAAHAAAADLAAA' AND ORA_ROWSCN = '3214916'
UPDATE "DAVEDBA"."PET" SET SPECIESID = '4', BREEDID = '43', GENDERID = '3', COLORING = 'Greenish Brown', BIRTH_DATE = TO_DATE('2010-06-23 14:25:41', 'YYYY-MM-DD HH24:MI:SS'), IS_LIVING = 'Y' WHERE ROWID = 'AAAWmCAAHAAAADLAAB' AND ORA_ROWSCN = '3214916'
UPDATE "DAVEDBA"."PET" SET SPECIESID = '2', BREEDID = '47', GENDERID = '4', COLORING = 'Brown/Tan', BIRTH_DATE = TO_DATE('2009-03-21 14:26:16', 'YYYY-MM-DD HH24:MI:SS'), IS_LIVING = 'y' WHERE ROWID = 'AAAWmCAAHAAAADLAAC' AND ORA_ROWSCN = '3214916'
UPDATE "DAVEDBA"."PET" SET SPECIESID = '2', BREEDID = '58', GENDERID = '3', COLORING = 'White base brown & black', BIRTH_DATE = TO_DATE('2009-08-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), IS_LIVING = '1' WHERE ROWID = 'AAAWmCAAHAAAADLAAD' AND ORA_ROWSCN = '3214916'
UPDATE "DAVEDBA"."PET" SET SPECIESID = '2', BREEDID = '48', GENDERID = '2', COLORING = 'Brown', BIRTH_DATE = TO_DATE('2000-01-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), IS_LIVING = 'Y' WHERE ROWID = 'AAAWmCAAHAAAADLAAE' AND ORA_ROWSCN = '3214916'
UPDATE "DAVEDBA"."PET" SET SPECIESID = '3', BREEDID = '54', GENDERID = '4', COLORING = 'No fur, only skin', BIRTH_DATE = TO_DATE('2007-03-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), IS_LIVING = 'Y' WHERE ROWID = 'AAAWmCAAHAAAADLAAF' AND ORA_ROWSCN = '3214916'
UPDATE "DAVEDBA"."PET" SET SPECIESID = '2', BREEDID = '57', GENDERID = '4', COLORING = 'White & Black', BIRTH_DATE = TO_DATE('2008-06-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), IS_LIVING = 'Y' WHERE ROWID = 'AAAWmCAAHAAAADLAAG' AND ORA_ROWSCN = '3214916'
UPDATE "DAVEDBA"."PET" SET SPECIESID = '1', BREEDID = '44', GENDERID = '6', COLORING = 'Yellow', BIRTH_DATE = TO_DATE('2000-02-22 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), IS_LIVING = 'Y' WHERE ROWID = 'AAAWmCAAHAAAADLAAH' AND ORA_ROWSCN = '3214916'

