CREATE OR REPLACE PROCEDURE PROC_PATHOL_ORDER(
	p_petid IN PATHOLOGY_HISTORY.PETID%TYPE, 
	p_vetid IN PATHOLOGY_HISTORY.VETID%TYPE,
	p_labid IN PATHOLOGY_HISTORY.LABID%TYPE
	)
/*USED BY VETS TO PLACE AN ORDER INTO THE PATHOLOGY LAB*/
AS

lv_laborderid PATHOLOGY_HISTORY.LABORDERID%TYPE;

BEGIN

	INSERT INTO PATHOLOGY_HISTORY(PETID, VETID, LABID)
		VALUES (p_petid, p_vetid, p_labid)
			RETURNING LABORDERID INTO lv_laborderid;
	COMMIT;

	INSERT INTO PATHOLOGY_LAB_ORDERS(LABORDERID, PETID, VETID, LABID, DATE_ORDERED)
		VALUES(lv_laborderid,p_petid, p_vetid, p_labid, SYSDATE);
	COMMIT;
END;


--TEST 
EXECUTE PROC_PATHOL_ORDER(1, 16, 8); 
EXECUTE PROC_PATHOL_ORDER (3, 18, 7); 
EXECUTE PROC_PATHOL_ORDER(23, 10, 11);
