CREATE OR REPLACE PROCEDURE PROC_EXPIRE_EST
AS
BEGIN
	DELETE FROM ESTIMATE
	WHERE TRUNC(DATE_ESTIMATE_CREATION) <= TRUNC(SYSDATE) - 30;
COMMIT;
EXCEPTION 
	WHEN NO_DATA_FOUND THEN 
	DBMS_OUTPUT.PUT_LINE('No expired estimates today!');
END;

