CREATE OR REPLACE PROCEDURE PROC_GETINVNUM(p_petid IN int, p_invid OUT int)
AS
BEGIN
SELECT *
INTO p_invid
FROM (SELECT  INVOICEID
FROM INVOICE_OPEN
WHERE trunc(DATE_INVOICE_CREATION) = TRUNC(SYSDATE) AND PETID = p_petid
ORDER BY LINEID DESC)
WHERE ROWNUM=1;

DBMS_OUTPUT.PUT_LINE(p_invid);

EXCEPTION WHEN NO_DATA_FOUND THEN --WHEN NO DATA FOUND GENERATE AN INVOICE ID
	SELECT INVOICE_SEQ.nextval
    INTO p_invid
    FROM DUAL;
INSERT INTO INVOICE_OPEN(INVOICEID, PETID, DATE_INVOICE_CREATION, ADD_ONS_DESCRIPTION, INDIVIDUAL_ADD_ON_COST, LINE_SUBTOTAL)
	VALUES(p_invid, p_petid, SYSDATE, 'New Invoice Start',0.00, NULL );
COMMIT;
END;