SELECT TABLE_NAME, COLUMN_NAME
FROM USER_TAB_COLUMNS  utb
WHERE LOWER(COLUMN_NAME) LIKE '%notes%'
AND utb.TABLE_NAME IN ( SELECT TABLE_NAME
                    FROM ALL_TABLES
                    WHERE OWNER = 'DAVEDBA'
                    AND TABLESPACE_NAME IN ('CHART'));