--------------------------------------------------------
--  File created - Saturday-June-23-2018   
--------------------------------------------------------
REM INSERTING into STAFF
SET DEFINE OFF;
INSERT INTO STAFF (STAFF_FIRST_NAME,STAFF_LAST_NAME,EMPLOYMENT_DATE,TERMINATION_DATE,IS_REHIREABLE,IS_VET,DATABASE_ROLE) VALUES ('Javier','Ramos',to_date('12-OCT-04','DD-MON-RR'),null,null,'0',null);
INSERT INTO STAFF (STAFF_FIRST_NAME,STAFF_LAST_NAME,EMPLOYMENT_DATE,TERMINATION_DATE,IS_REHIREABLE,IS_VET,DATABASE_ROLE) VALUES ('Emma','Summers',to_date('03-MAR-11','DD-MON-RR'),null,null,'1',null);
INSERT INTO STAFF (STAFF_FIRST_NAME,STAFF_LAST_NAME,EMPLOYMENT_DATE,TERMINATION_DATE,IS_REHIREABLE,IS_VET,DATABASE_ROLE) VALUES ('Ororo','Rogers',null,null,null,'Y',null);
INSERT INTO STAFF (STAFF_FIRST_NAME,STAFF_LAST_NAME,EMPLOYMENT_DATE,TERMINATION_DATE,IS_REHIREABLE,IS_VET,DATABASE_ROLE) VALUES ('Eric','Xavier',null,null,null,'y',null);
INSERT INTO STAFF (STAFF_FIRST_NAME,STAFF_LAST_NAME,EMPLOYMENT_DATE,TERMINATION_DATE,IS_REHIREABLE,IS_VET,DATABASE_ROLE) VALUES ('Dave','Babler',to_date('20-MAY-18', 'DD-MON-RR',null,null,'y',null);



