


SELECT COALESCE(TO_CHAR(af.PETID), TO_CHAR(af.BIRTH_DATE), TO_CHAR(af.BREEDID), TO_CHAR(af.GENDERID), TO_CHAR(af.SPECIESID), TO_CHAR(af.TEMPERAMENT_NOTES), TO_CHAR(vph.VET_PROCEDUREID),  TO_CHAR(vph.VET_PROCEDURE_DATE), TO_CHAR(vph.VET_PROCEDURE_NOTES),
  TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_DATE), TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_OUTCOME), TO_CHAR(ph.LABID),  TO_CHAR(ph.DATE_COMPLETED),  TO_CHAR(ph.RESULTS),
  TO_CHAR(ph.CRITICAL_DISEASE), TO_CHAR(rxh.DRUGID), TO_CHAR(rxh.DRUG_DOSAGE), TO_CHAR(rxh.DRUG_UNITS_PRESCRIBED), TO_CHAR(rxh.DATE_WRITTEN), TO_CHAR(rxh.NOTES), TO_CHAR(eh.ENCOUNTER_WEIGHT), TO_CHAR(eh.ENCOUNTER_DATE_TIME), TO_CHAR(eh.ENCOUNTER_NOTES), TO_CHAR(rh.RADIMG_DATE_TAKEN), TO_CHAR(rh.RADIMG_NOTES))
FROM ANIMAL_FACTS af FULL OUTER JOIN VET_PROCEDURE_HISTORY vph
  ON af.PETID = vph.PETID FULL OUTER JOIN PATHOLOGY_HISTORY ph
  ON af.PETID = ph.PETID FULL OUTER JOIN RX_HISTORY rxh
  ON af.PETID = rxh.PETID FULL OUTER JOIN  ENCOUNTER_HISTORY eh
  ON af.PETID = eh.PETID FULL OUTER JOIN RADIOLOGY_HISTORY rh
  ON af.PETID = rh.PETID
  
  GROUP BY COALESCE(TO_CHAR(af.PETID), TO_CHAR(af.BIRTH_DATE), TO_CHAR(af.BREEDID), TO_CHAR(af.GENDERID), TO_CHAR(af.SPECIESID), TO_CHAR(af.TEMPERAMENT_NOTES), TO_CHAR(vph.VET_PROCEDUREID),  TO_CHAR(vph.VET_PROCEDURE_DATE), TO_CHAR(vph.VET_PROCEDURE_NOTES),
  TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_DATE), TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_OUTCOME), TO_CHAR(ph.LABID),  TO_CHAR(ph.DATE_COMPLETED),  TO_CHAR(ph.RESULTS),
  TO_CHAR(ph.CRITICAL_DISEASE), TO_CHAR(rxh.DRUGID), TO_CHAR(rxh.DRUG_DOSAGE), TO_CHAR(rxh.DRUG_UNITS_PRESCRIBED), TO_CHAR(rxh.DATE_WRITTEN), TO_CHAR(rxh.NOTES), TO_CHAR(eh.ENCOUNTER_WEIGHT), TO_CHAR(eh.ENCOUNTER_DATE_TIME), TO_CHAR(eh.ENCOUNTER_NOTES), TO_CHAR(rh.RADIMG_DATE_TAKEN), TO_CHAR(rh.RADIMG_NOTES));






  SELECT af.PETID, af.BIRTH_DATE, af.BREEDID, af.GENDERID, af.SPECIESID, af.TEMPERAMENT_NOTES, vph.VET_PROCEDUREID,  vph.VET_PROCEDURE_DATE, TO_CHAR(vph.VET_PROCEDURE_NOTES) as VET_PROCEDURE_NOTES,
  vph.VET_PROCEDURE_FOLLOWUP_DATE, TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_OUTCOME) as PROCEDURE_FOLLOWUP_OUTCOME,  ph.LABID,  ph.DATE_COMPLETED,  TO_CHAR(ph.RESULTS) as PROCEDURE_RESULTS,
  ph.CRITICAL_DISEASE, rxh.DRUGID, rxh.DRUG_DOSAGE, rxh.DRUG_UNITS_PRESCRIBED, rxh.DATE_WRITTEN, TO_CHAR(rxh.NOTES) AS RX_NOTES, eh.ENCOUNTER_WEIGHT, eh.ENCOUNTER_DATE_TIME, TO_CHAR(eh.ENCOUNTER_NOTES) AS ENCOUNTER_NOTES, rh.RADIMG_DATE_TAKEN, TO_CHAR(rh.RADIMG_NOTES) as RADIMG_NOTES
FROM ANIMAL_FACTS af FULL OUTER JOIN VET_PROCEDURE_HISTORY vph
  ON af.PETID = vph.PETID FULL OUTER JOIN PATHOLOGY_HISTORY ph
  ON af.PETID = ph.PETID FULL OUTER JOIN RX_HISTORY rxh
  ON af.PETID = rxh.PETID FULL OUTER JOIN  ENCOUNTER_HISTORY eh
  ON af.PETID = eh.PETID FULL OUTER JOIN RADIOLOGY_HISTORY rh
  ON af.PETID = rh.PETID;





SELECT *
FROM(
 SELECT af.PETID, af.BIRTH_DATE, af.BREEDID, af.GENDERID, af.SPECIESID, af.TEMPERAMENT_NOTES, vph.VET_PROCEDUREID,  vph.VET_PROCEDURE_DATE, TO_CHAR(vph.VET_PROCEDURE_NOTES) as VET_PROCEDURE_NOTES,
  vph.VET_PROCEDURE_FOLLOWUP_DATE, TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_OUTCOME) as PROCEDURE_FOLLOWUP_OUTCOME, 
  		rank() over (partition by af.PETID ORDER BY vph.VET_PROCEDURE_DATE ) rnk, 
  ph.LABID,  ph.DATE_COMPLETED,  TO_CHAR(ph.RESULTS) as PROCEDURE_RESULTS,  ph.CRITICAL_DISEASE, 
		rank() over (partition by af.PETID ORDER BY ph.DATE_COMPLETED ) rnk2, 
  rxh.DRUGID, rxh.DRUG_DOSAGE, rxh.DRUG_UNITS_PRESCRIBED, rxh.DATE_WRITTEN, TO_CHAR(rxh.NOTES) AS RX_NOTES,  
  		rank() over (partition by af.PETID ORDER BY rxh.DATE_WRITTEN ) rnk3, 
  eh.ENCOUNTER_WEIGHT, eh.ENCOUNTER_DATE_TIME, TO_CHAR(eh.ENCOUNTER_NOTES) AS ENCOUNTER_NOTES,
  		rank() over (partition by af.PETID ORDER BY eh.ENCOUNTER_DATE_TIME ) rnk4, 
   rh.RADIMG_DATE_TAKEN, TO_CHAR(rh.RADIMG_NOTES) as RADIMG_NOTES, 
		rank() over (partition by af.PETID ORDER BY rh.RADIMG_DATE_TAKEN ) rnk5, 
  FROM ANIMAL_FACTS af FULL OUTER JOIN VET_PROCEDURE_HISTORY vph 
  ON af.PETID = vph.PETID FULL OUTER JOIN PATHOLOGY_HISTORY ph
  ON af.PETID = ph.PETID FULL OUTER JOIN RX_HISTORY rxh
  ON af.PETID = rxh.PETID FULL OUTER JOIN  ENCOUNTER_HISTORY eh
  ON af.PETID = eh.PETID FULL OUTER JOIN RADIOLOGY_HISTORY rh
  ON af.PETID = rh.PETID)
WHERE rnk = 1 
AND rnk2 < 2
AND rnk3 < 3
AND rnk4 < 4
AND rnk5 < 5;

SELECT rank() over (partition by af.PETID ORDER BY vph.VET_PROCEDURE_DATE )
FROM ANIMAL_FACTS af FULL OUTER JOIN VET_PROCEDURE_HISTORY vph 
  ON af.PETID = vph.PETID;


SELECT rank() over (partition by af.PETID ORDER BY ph.DATE_COMPLETED )
  FROM  ANIMAL_FACTS af FULL OUTER JOIN PATHOLOGY_HISTORY ph
   ON af.PETID = ph.PETID;

SELECT rank() over (partition by af.PETID ORDER BY rxh.DATE_WRITTEN )
FROM ANIMAL_FACTS af FULL OUTER JOIN RX_HISTORY rxh
	ON af.PETID = rxh.PETID;


SELECT rank() over (partition by af.PETID ORDER BY eh.ENCOUNTER_DATE_TIME )
FROM ANIMAL_FACTS af FULL OUTER JOIN ENCOUNTER_HISTORY eh
	ON af.PETID = eh.PETID;

SELECT rank() over (partition by af.PETID ORDER BY rh.RADIMG_DATE_TAKEN )
FROM ANIMAL_FACTS af FULL OUTER JOIN RADIOLOGY_HISTORY rh
	ON af.PETID = rh.PETID;