	CURSOR cur_encounter IS 
	SELECT PETID, TO_CHAR(TRUNC(ENCOUNTER_DATE_TIME)), ENCOUNTER_WEIGHT, ENCOUNTER_NOTES 
    FROM ENCOUNTER_HISTORY 
	WHERE PETID = f_petid
	ORDER BY ENCOUNTER_DATE_TIME;
   
   CURSOR cur_radiol IS 
   SELECT PETID, TO_CHAR(TRUNC(RADIMG_DATE_TAKEN)), RADIMG_NOTES
   FROM RADIOLOGY_HISTORY
   WHERE PETID = f_petid
   ORDER BY RADIMG_DATE_TAKEN;

   CURSOR cur_proc IS
   SELECT PETID, TO_CHAR(TRUNC(VET_PROCEDURE_DATE)),  PROC_DATE, FUNC_VET_NAME(VETID), RX_DISPENSED_DURING, VET_PROCEDURE_NOTES, TO_CHAR(TRUNC(VET_PROCEDURE_FOLLOWUP_DATE)), VET_PROCEDURE_FOLLOWUP_OUTCOME
   FROM VET_PROCEDURE_HISTORY
   WHERE PETID = f_petid
   ORDER BY ;

   CURSOR cur_path IS
   SELECT PETID,TO_CHAR(TRUNC(DATE_COMPLETED)), FUNC_LAB_NAME(LABID), FUNC_VET_NAME(VETID), CRITICAL_DISEASE, RESULTS
   FROM PATHOLOGY_HISTORY
