SELECT  v1.RXID, v1.PETID, PET_NAME, VET_NAME, DRUGID, DRUG_NAME, DRUG_DOSAGE, IS_MAINTENANCE_MED, DRUG_UNITS_PRESCRIBED, TIMES_PER_DAY, DATE_WRITTEN, NOTES, v1.PATIENT_VET_PROCEDUREID, v2.procedure_event
FROM RX_DETAILS_V v1 FULL OUTER JOIN (SELECT DISTINCT PATIENT_VET_PROCEDUREID, procedure_event FROM RX_FROM_CLINPROC4JOIN_V) v2
ON v1.PATIENT_VET_PROCEDUREID = v2.PATIENT_VET_PROCEDUREID
WHERE v1.PATIENT_VET_PROCEDUREID IS NULL OR
v1.PATIENT_VET_PROCEDUREID IN  (SELECT DISTINCT PATIENT_VET_PROCEDUREID FROM RX_FROM_CLINPROC4JOIN_V) ;
