CREATE OR REPLACE VIEW CHART_HEAD_V
AS
SELECT PETID, CHART_PKG.FUNC_CHART_NAME(PETID) AS "Animal Name", FUNC_SPECIES(SPECIESID) AS "Species", FUNC_BREED(BREEDID) as "Breed", FUNC_GENDER(GENDERID) as "Gender", TO_NUMBER(TRUNC(MONTHS_BETWEEN(SYSDATE,BIRTH_DATE)/12, 1)) as "Age", TEMPERAMENT_NOTES as "Disposition"
	FROM ANIMAL_FACTS 
 WHERE DEATH_DATE IS NULL;