CREATE MATERIALIZED VIEW CHART_META_GROUPED_SETS_MV 
      REFRESH COMPLETE START WITH (SYSDATE) NEXT  (SYSDATE+1/1440) WITH ROWID
AS
SELECT af.PETID, af.BIRTH_DATE, af.BREEDID, af.GENDERID, af.SPECIESID, af.TEMPERAMENT_NOTES, vph.VET_PROCEDUREID,  vph.VET_PROCEDURE_DATE, TO_CHAR(vph.VET_PROCEDURE_NOTES) as VET_PROCEDURE_NOTES,
  vph.VET_PROCEDURE_FOLLOWUP_DATE, TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_OUTCOME) as PROCEDURE_FOLLOWUP_OUTCOME,  ph.LABID,  ph.DATE_COMPLETED,  TO_CHAR(ph.RESULTS) as PROCEDURE_RESULTS,
  ph.CRITICAL_DISEASE, rxh.DRUGID, rxh.DRUG_DOSAGE, rxh.DRUG_UNITS_PRESCRIBED, rxh.DATE_WRITTEN, TO_CHAR(rxh.NOTES) AS RX_NOTES, eh.ENCOUNTER_WEIGHT, eh.ENCOUNTER_DATE_TIME, TO_CHAR(eh.ENCOUNTER_NOTES) AS ENCOUNTER_NOTES, rh.RADIMG_DATE_TAKEN, TO_CHAR(rh.RADIMG_NOTES) as RADIMG_NOTES
FROM ANIMAL_FACTS af FULL OUTER JOIN VET_PROCEDURE_HISTORY vph
  ON af.PETID = vph.PETID FULL OUTER JOIN PATHOLOGY_HISTORY ph
  ON af.PETID = ph.PETID FULL OUTER JOIN RX_HISTORY rxh
  ON af.PETID = rxh.PETID FULL OUTER JOIN  ENCOUNTER_HISTORY eh
  ON af.PETID = eh.PETID FULL OUTER JOIN RADIOLOGY_HISTORY rh
  ON af.PETID = rh.PETID;
  GROUP BY GROUPING SETS ( af.PETID, af.BIRTH_DATE,  af.BREEDID, af.GENDERID, af.SPECIESID, af.TEMPERAMENT_NOTES, vph.VET_PROCEDUREID,  vph.VET_PROCEDURE_DATE, TO_CHAR(vph.VET_PROCEDURE_NOTES),
  vph.VET_PROCEDURE_FOLLOWUP_DATE, TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_OUTCOME),  ph.LABID,  ph.DATE_COMPLETED,  TO_CHAR(ph.RESULTS),
  ph.CRITICAL_DISEASE, rxh.DRUGID, rxh.DRUG_DOSAGE, rxh.DRUG_UNITS_PRESCRIBED, rxh.DATE_WRITTEN, TO_CHAR(rxh.NOTES), eh.ENCOUNTER_WEIGHT, eh.ENCOUNTER_DATE_TIME, TO_CHAR(eh.ENCOUNTER_NOTES), rh.RADIMG_DATE_TAKEN, TO_CHAR(rh.RADIMG_NOTES));


CREATE OR REPLACE VIEW CHART_META_GROUPED_SETS_V
AS
SELECT PETID, CHART_PKG.FUNC_CHART_NAME(PETID) AS PATIENT_NAME, FUNC_OWNER_NAME(PETID) AS OWNER_NAME, FUNC_ALL_SIBLING_BREEDS(PETID) AS PET_SIBLINGS,
BIRTH_DATE,
FUNC_BREED(BREEDID) AS BREED,
FUNC_GENDER(GENDERID) AS GENDER,
FUNC_SPECIES(SPECIESID) AS SPECIES,
TEMPERAMENT_NOTES,
FUNC_PROCNAME(VET_PROCEDUREID) AS CLINICAL_PROCEDURE,
VET_PROCEDURE_DATE,
VET_PROCEDURE_NOTES,
VET_PROCEDURE_FOLLOWUP_DATE,
PROCEDURE_FOLLOWUP_OUTCOME,
FUNC_LAB_NAME(LABID) AS PATHOLOGY_LAB,
DATE_COMPLETED,
PROCEDURE_RESULTS,
CRITICAL_DISEASE,
FUNC_DRUGNAME(DRUGID) AS DRUG_NAME,
DRUG_DOSAGE,
DRUG_UNITS_PRESCRIBED,
DATE_WRITTEN,
RX_NOTES,
ENCOUNTER_WEIGHT,
ENCOUNTER_DATE_TIME,
ENCOUNTER_NOTES,
RADIMG_DATE_TAKEN,
RADIMG_NOTES
FROM CHART_META_GROUPED_SETS_MV 
ORDER BY PETID;
-----------------------------------------------
CREATE  MATERIALIZED VIEW CHART_META_MV 
      REFRESH COMPLETE START WITH (SYSDATE) NEXT  (SYSDATE+1/1440) WITH ROWID
AS
SELECT *
FROM(
 SELECT af.PETID, af.BIRTH_DATE, af.BREEDID, af.GENDERID, af.SPECIESID, af.TEMPERAMENT_NOTES, vph.VET_PROCEDUREID,  vph.VET_PROCEDURE_DATE, TO_CHAR(vph.VET_PROCEDURE_NOTES) as VET_PROCEDURE_NOTES,
  vph.VET_PROCEDURE_FOLLOWUP_DATE, TO_CHAR(vph.VET_PROCEDURE_FOLLOWUP_OUTCOME) as PROCEDURE_FOLLOWUP_OUTCOME, 
      rank() over (partition by af.PETID ORDER BY vph.VET_PROCEDURE_DATE ) rnk, 
  ph.LABID,  ph.DATE_COMPLETED,  TO_CHAR(ph.RESULTS) as PROCEDURE_RESULTS,  ph.CRITICAL_DISEASE, 
    rank() over (partition by af.PETID ORDER BY ph.DATE_COMPLETED ) rnk2, 
  rxh.DRUGID, rxh.DRUG_DOSAGE, rxh.DRUG_UNITS_PRESCRIBED, rxh.DATE_WRITTEN, TO_CHAR(rxh.NOTES) AS RX_NOTES,  
      rank() over (partition by af.PETID ORDER BY rxh.DATE_WRITTEN ) rnk3, 
  eh.ENCOUNTER_WEIGHT, eh.ENCOUNTER_DATE_TIME, TO_CHAR(eh.ENCOUNTER_NOTES) AS ENCOUNTER_NOTES,
      rank() over (partition by af.PETID ORDER BY eh.ENCOUNTER_DATE_TIME ) rnk4, 
   rh.RADIMG_DATE_TAKEN, TO_CHAR(rh.RADIMG_NOTES) as RADIMG_NOTES, 
    rank() over (partition by af.PETID ORDER BY rh.RADIMG_DATE_TAKEN ) rnk5
  FROM ANIMAL_FACTS af FULL OUTER JOIN VET_PROCEDURE_HISTORY vph 
  ON af.PETID = vph.PETID FULL OUTER JOIN PATHOLOGY_HISTORY ph
  ON af.PETID = ph.PETID FULL OUTER JOIN RX_HISTORY rxh
  ON af.PETID = rxh.PETID FULL OUTER JOIN  ENCOUNTER_HISTORY eh
  ON af.PETID = eh.PETID FULL OUTER JOIN RADIOLOGY_HISTORY rh
  ON af.PETID = rh.PETID)
WHERE /*rnk in (SELECT rank() over (partition by af.PETID ORDER BY vph.VET_PROCEDURE_DATE )
FROM ANIMAL_FACTS af FULL OUTER JOIN VET_PROCEDURE_HISTORY vph 
  ON af.PETID = vph.PETID ) 
AND rnk2 IN (SELECT rank() over (partition by af.PETID ORDER BY ph.DATE_COMPLETED )
  FROM  ANIMAL_FACTS af FULL OUTER JOIN PATHOLOGY_HISTORY ph
   ON af.PETID = ph.PETID)
AND rnk3 IN (SELECT rank() over (partition by af.PETID ORDER BY rxh.DATE_WRITTEN )
FROM ANIMAL_FACTS af FULL OUTER JOIN RX_HISTORY rxh
  ON af.PETID = rxh.PETID)
AND */ rnk4 IN (SELECT rank() over (partition by af.PETID ORDER BY eh.ENCOUNTER_DATE_TIME )
FROM ANIMAL_FACTS af FULL OUTER JOIN ENCOUNTER_HISTORY eh
  ON af.PETID = eh.PETID)
AND rnk5 IN (SElECT rank() over (partition by af.PETID ORDER BY rh.RADIMG_DATE_TAKEN )
FROM ANIMAL_FACTS af FULL OUTER JOIN RADIOLOGY_HISTORY rh
  ON af.PETID = rh.PETID)
;


CREATE OR REPLACE VIEW CHART_META_V
AS
SELECT PETID, CHART_PKG.FUNC_CHART_NAME(PETID) AS PATIENT_NAME, FUNC_OWNER_NAME(PETID) AS OWNER_NAME, FUNC_ALL_SIBLING_BREEDS(PETID) AS PET_SIBLINGS,
BIRTH_DATE,
FUNC_BREED(BREEDID) AS BREED,
FUNC_GENDER(GENDERID) AS GENDER,
FUNC_SPECIES(SPECIESID) AS SPECIES,
TEMPERAMENT_NOTES,
FUNC_PROCNAME(VET_PROCEDUREID) AS CLINICAL_PROCEDURE,
VET_PROCEDURE_DATE,
VET_PROCEDURE_NOTES,
VET_PROCEDURE_FOLLOWUP_DATE,
PROCEDURE_FOLLOWUP_OUTCOME,
FUNC_LAB_NAME(LABID) AS PATHOLOGY_LAB,
DATE_COMPLETED,
PROCEDURE_RESULTS,
CRITICAL_DISEASE,
FUNC_DRUGNAME(DRUGID) AS DRUG_NAME,
DRUG_DOSAGE,
DRUG_UNITS_PRESCRIBED,
DATE_WRITTEN,
RX_NOTES,
ENCOUNTER_WEIGHT,
ENCOUNTER_DATE_TIME,
ENCOUNTER_NOTES,
RADIMG_DATE_TAKEN,
RADIMG_NOTES
FROM CHART_META_MV 
ORDER BY PETID;