CREATE OR REPLACE VIEW CHART_NOTES_V
AS

SELECT PETID AS PETID, TO_CLOB(FUNC_VET_NAME(VETID)) AS VET, TRUNC(DATE_COMPLETED) as "EVENT_DATE", TO_CLOB(FUNC_LAB_NAME(LABID)) AS EVENT, TO_CLOB(CRITICAL_DISEASE) AS CRITDISEASE, TO_CLOB(RESULTS) AS NOTES, FUNC_DUALCLOB('PATHOLOGY') AS EVENT_TYPE
FROM PATHOLOGY_HISTORY
UNION ALL
SELECT PETID, TO_CLOB(FUNC_VET_NAME(VETID)), TRUNC(VET_PROCEDURE_DATE) as date_done, TO_CLOB(FUNC_PROCNAME(VET_PROCEDUREID)), TO_CLOB(NULL), TO_CLOB(VET_PROCEDURE_NOTES), FUNC_DUALCLOB('CLINICAL_PROCEDURE')
FROM VET_PROCEDURE_HISTORY
UNION ALL
SELECT PETID, TO_CLOB(NULL), TRUNC(RADIMG_DATE_TAKEN), TO_CLOB(NULL), TO_CLOB(NULL), TO_CLOB(RADIMG_NOTES), FUNC_DUALCLOB('RADIOLOGY')
FROM RADIOLOGY_HISTORY
UNION ALL
SELECT PETID, TO_CLOB(FUNC_VET_STAFF(VETID)), TRUNC(ENCOUNTER_DATE_TIME), TO_CLOB(ENCOUNTER_WEIGHT), NULL, TO_CLOB(ENCOUNTER_NOTES), FUNC_DUALCLOB('ENCOUNTER')
FROM ENCOUNTER_HISTORY;
