CREATE OR REPLACE FORCE EDITIONABLE VIEW CUSTOMER_INVOICE_V AS 
SELECT io.INVOICEID, FUNC_CHECK_IN_NAME(io.PETID) AS PET_NAME, io.DATE_INVOICE_CREATION, FUNC_DRUGNAME(DRUGID) AS RX, RX_COST,
	   FUNC_LAB_NAME(LABID) AS LAB, LAB_COST, SPECIALTY_ADD_ON_COST, SPECIALTYID, FUNC_PROCNAME( VET_PROCEDUREID) AS CLINICAL_PROCEDURE,
	   PROCEDURE_COST, ADD_ONS_DESCRIPTION, INDIVIDUAL_ADD_ON_COST,  OR_FEE, LINE_SUBTOTAL, LATE_FEE, GRAND_TOTAL AS LINE_SUB_WITH_FEE, invoice_total from INVOICE_OPEN io
JOIN (select q.invoiceid, sum(q.GRAND_TOTAL)as INVOICE_TOTAL  
	from INVOICE_OPEN q 
	group by q.INVOICEID) j 
ON io.INVOICEID = j.INVOICEID;
