  CREATE OR REPLACE VIEW DAILY_PROCRX_V
  AS
  SELECT vph.PETID, FUNC_CHECK_IN_NAME(vph.PETID) AS "Pet Name", vph.VETID,  FUNC_VET_NAME(vph.VETID) AS "Veterinarian", ro.DRUG_UNITS_PRESCRIBED, ro.DRUG_UNITS_DISPENSED, vph.VET_PROCEDURE_NOTES, ro.DRUGID, ro.RXID
FROM VET_PROCEDURE_HISTORY vph JOIN RX_HISTORY rh
	ON vph.PATIENT_VET_PROCEDUREID = rh.PATIENT_VET_PROCEDUREID
	JOIN RX_ORDER ro ON 
	rh.RXID = ro.RXID
WHERE vph.RX_DISPENSED_DURING IN ('1', 'Y', 'y') 
	AND ro.FILLED_BY IS NULL
	AND TRUNC(vph.VET_PROCEDURE_DATE) = TRUNC(SYSDATE);

/*REPORT SHOWS WHAT PROCEDURES WERE DONE THAT DAY WITH MEDICINE
DISPENSED DURING THE PROCEDURE SO THE CHARTS CAN BE
UPDATED BY PHARMACISTS/VETS BEFORE CLOSE OF BUSINESS

This is both common sense and a regulation, when you've got 
an animal crashing and you need to administer meds quickly you
don't want to have to write it down that second*/