CREATE OR REPLACE VIEW ESTIMATE_V
AS
select e.ESTIMATEID, FUNC_CHECK_IN_NAME(e.PETID) AS PET_NAME, e.DATE_ESTIMATE_CREATION, FUNC_DRUGNAME(DRUGID) AS RX, RX_COST, FUNC_LAB_NAME(LABID) AS LAB, LAB_COST, SPECIALTY_ADD_ON_COST, SPECIALTYID, FUNC_PROCNAME( VET_PROCEDUREID) AS CLINICAL_PROCEDURE, PROCEDURE_COST, ADD_ONS_DESCRIPTION, INDIVIDUAL_ADD_ON_COST,  OR_FEE, LINE_SUBTOTAL, grand_total
from estimate e
join (select q.estimateid, sum(q.LINE_SUBTOTAL) as grand_total from estimate q group by q.estimateid) j on e.estimateid = j.estimateid;

