CREATE OR REPLACE VIEW PATH_LABS_OPEN_V
AS
	SELECT LABORDERID, LABID, FUNC_LAB_NAME(LABID) AS "Lab Name", FUNC_CHECK_IN_NAME(PETID) AS "For", PETID AS "Patient Chart #", KITS_ON_HAND AS "Availible Kits"
	FROM PATHOLOGY_LAB_ORDERS JOIN PATHOLOGY_LAB_TESTS USING(LABID)
	WHERE TRUNC(DATE_ORDERED) = TRUNC(SYSDATE) AND DATE_COMPLETED IS NULL;
