CREATE MATERIALIZED VIEW PHARMA_STOCK_MV
      REFRESH COMPLETE START WITH (SYSDATE) NEXT  SYSDATE+1 
AS
	SELECT DRUGID, DRUG_NAME, DRUG_DOSAGE, (CASE WHEN REORDER_FLAG IN ('1', 'y', 'Y', 't', 'T') THEN 'ORDER MORE' ELSE NULL END) as "Reorder?" ,  
	DRUG_UNITS_INV, ORDER_LEVEL,  DATE_STOCKED, DATE_EXPIRATION
	FROM PHARMACOLOGY_STOCK;

