CREATE OR REPLACE VIEW RX_DETAILS_V AS 
SELECT rh.RXID, rh.PETID, CHART_PKG.FUNC_CHART_NAME(rh.PETID) AS PET_NAME, FUNC_VET_NAME(rh.VETID) AS VET_NAME,  rh.DRUGID, ps.DRUG_NAME, rh.DRUG_DOSAGE, rh.IS_MAINTENANCE_MED, rh.DRUG_UNITS_PRESCRIBED, rh.TIMES_PER_DAY, rh.DATE_WRITTEN, rh.NOTES, rh.PATIENT_VET_PROCEDUREID, FUNC_PROCNAME(vph.VET_PROCEDUREID) AS CLINICAL_EVENT
FROM RX_HISTORY rh JOIN PHARMACOLOGY_STOCK ps 
	ON rh.DRUGID = ps.DRUGID
FULL OUTER JOIN VET_PROCEDURE_HISTORY vph
	ON rh.PATIENT_VET_PROCEDUREID = vph.PATIENT_VET_PROCEDUREID
WHERE (rh.DRUGID, ps.DRUG_NAME) IN (SELECT DRUGID, DRUG_NAME FROM PHARMACOLOGY_STOCK)
AND ( rh.PATIENT_VET_PROCEDUREID IN  (SELECT DISTINCT PATIENT_VET_PROCEDUREID FROM VET_PROCEDURE_HISTORY) OR rh.PATIENT_VET_PROCEDUREID IS NULL)
;



