--PHARMACOLOGY IN STOCK
CREATE OR REPLACE VIEW PHARMACOLOGY_ON_HAND_V
AS
SELECT DRUGID, DRUG_NAME,  DRUG_DOSAGE, DRUG_UNITS_INV,  IS_CONTROLLED,  DATE_STOCKED,  DATE_EXPIRATION 
FROM PHARMACOLOGY_STOCK ;

--REPORT ON BLOOD ON HAND
CREATE OR REPLACE VIEW BLOOD_REPORT_V
AS
SELECT COUNT(BLOODBAGID) AS TOTAL_BAGS, NVL(FUNC_SPECIES(SPECIESID), 'Grand Total') AS SPECIES 
FROM LOCAL_BLOOD_BANK  
GROUP BY CUBE (SPECIESID);